### ISSUE TITLE
Can't filter blobs with multidownload_blob src argument

### ISSUE THREAD

**Issue by angusrtaylor** [cloudyr/AzureStor#12]
I want to download all the blobs in a specific directory in a container but specifying the directory using the src argument does not filter the blobs. Here is an example. I want to only download the blobs in /batch_forecasting/models but instead it downloads all the blobs in the container:

`cont <- blob_container("https://happypathspublic.blob.core.windows.net/assets/")

list_blobs(cont)

multidownload_blob(
  cont,
  src = "/batch_forecasting/models/*",
  dest = "models",
  overwrite = TRUE
)`

**Comment by Hong-Revo** [comment]
Forgot that blobs can contain `/` in the name. Can you see if it works now?

**Comment by angusrtaylor** [comment]
@Hong-Revo thanks that works now. Very fast too!
