### ISSUE TITLE
Feature: Azcopy installation function

### ISSUE THREAD

**Issue by brnleehng** [cloudyr/AzureStor#16]
It would be nice to have a built-in azcopy installation so an R user doesn't need to go out of their RStudio session.

I've seen this in a couple of other tidyverse packages such as sparklyR, tensorflowR and kerasR

``` R
install_azcopy()
```

**Comment by Hong-Revo** [comment]
Well, you never need to leave your R session anyway... that's the whole point of having this package.

**Comment by brnleehng** [comment]
I want to use azcopy though for performance reasons in my RStudio session

**Comment by Hong-Revo** [comment]
This package isn't meant to be just a shell to azcopy, unlike the various packages like Keras or Tensorflow. Why don't you give the actual R code a shot and see how it goes. Even better, if you could help in adding features like retrying to AzureStor, that would be great!
