### ISSUE TITLE
is.character(headers) is not True bug

### ISSUE THREAD

**Issue by shihikoo** [cloudyr/AzureStor#2]
I used AzureStor in my code to upload and list files in a container and it works nice. I did get an error:

Within file "blob_client_funcs.R"
at line 317:  headers <- list("content-length"=nchar(body))
This will results class(unlist(headers)) = int rather than character 
As a result, an error is threw when calling the line 34 in "storage_utils.R"
    headers <- httr::add_headers(.headers=unlist(headers))
as:  "is.character(headers) is not True " 

In order to solve this issue, I changed: headers <- as.character(list("content-length"=nchar(body))) 

After the change, I can upload files successfully.

**Comment by Hong-Revo** [comment]
Hi, i don't see this error. What version of httr are you using?

**Comment by shihikoo** [comment]
1.4.0

**Comment by shihikoo** [comment]
Great. Thanks. This sounds correct to me.

I will try the new commits.

Thanks,
Jing
