### ISSUE TITLE
saving to blob without copying

### ISSUE THREAD

**Issue by nbbn** [cloudyr/AzureStor#4]
Hi Guys, thanks for developing this nice library.

I would like to upload to blob serialized data like RDS / json etc. without saving it to some temporary location. As I understand current functionality of library, I can only upload files (upload_blob). I would like to upload RDS file without saving it to some interim location. Any idea how to do it? If not, please treat it as feature request.
Thanks again,
Jakub

**Comment by Hong-Revo** [comment]
Hi, I actually have code in `upload_blob` to handle text connections, but it looks like a later update broke it. I'll fix this up for the next release.

**Comment by Hong-Revo** [comment]
This should now be fixed for blobs, files and ADLS. Give it a go and let me know if it doesn't work.
